config/routes.rb
CFPApp::Application.routes.draw do

  resources :notifications, only: [ :index, :show ] do
    post :mark_all_as_read, on: :collection
  end

  root 'home#show'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  get '/auth/failure' => 'sessions#new', error: true
  get '/signout' => 'sessions#destroy', as: :signout
  resource :session, only: [:new, :create, :destroy]

  resource :profile, only: [:edit, :update]
  resource :public_comments, only: [:create], controller: :comments, type: 'PublicComment'
  resource :internal_comments, only: [:create], controller: :comments, type: 'InternalComment'
  resources :speakers, only: [:destroy]
  resources :proposals, only: [:index]
  resources :events, only: [:index]
  scope '/events/:slug' do
    get '/' => 'events#show', as: :event

    post '/proposals' => 'proposals#create', as: :event_proposals
    get 'parse_edit_field' => 'proposals#parse_edit_field',
      as: :parse_edit_field_proposal

    resources :proposals, param: :uuid do
      member { get :confirm }
      member { post :set_confirmed }
      member { post :withdraw }
      member { delete :destroy}
    end
  end

  resources :participant_invitations, only: :show, param: :slug do
    member do
      get ":token/accept", action: :accept, as: :accept
      get ":token/refuse", action: :refuse, as: :refuse
    end
  end

	resources :invitations, only: [:show, :create, :destroy], param: :invitation_slug do
		member do
			post :accept, action: :update
			post :refuse, action: :update, refuse: true
			post :resend, action: :resend
		end
	end

  namespace 'admin' do
    resources :events, except: [:show, :edit, :update] do
      post :archive
      post :unarchive
    end

    resources :people
  end

  namespace 'organizer' do
    resources :events, only: [:edit, :show, :update] do
      resources :participant_invitations, except: [ :new, :edit, :update, :show ]

      controller :program do
        get 'program' => 'program#show'
      end

      resources :participants, only: [:create, :destroy, :update] do
        collection { get :emails, defaults: { format: :json } }
      end

      resources :rooms, only: [:create, :update, :destroy]
      resources :tracks, only: [:create, :destroy]
      resources :sessions, except: :show
      resources :proposals, param: :uuid do
        resources :speakers, only: [:new, :create]
        post :finalize
        post :update_state
      end

      controller :speakers do
        get :speaker_emails, action: :emails
      end
      resources :speakers, only: [:index, :show, :edit, :update, :destroy] do
        member do
          get :profile, to: "profiles#edit", as: :edit_profile
          patch :profile, to: "profiles#update", as: :update_profile
        end
      end
    end

  end

  namespace 'reviewer' do
    resources :events, only: [] do
      resources :proposals, only: [:index, :show, :update], param: :uuid do
        resources :ratings, only: [:create, :update], defaults: { format: :js }
      end
    end
  end

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/models/event.rb
class Event < ActiveRecord::Base
  store_accessor :speaker_notification_emails, :accept
  store_accessor :speaker_notification_emails, :reject
  store_accessor :speaker_notification_emails, :waitlist

  has_many :participants, dependent: :destroy
  has_many :proposals,    dependent: :destroy
  has_many :speakers,     through: :proposals
  has_many :rooms,        dependent: :destroy
  has_many :tracks,       dependent: :destroy
  has_many :sessions,       dependent: :destroy
  has_many :taggings, through: :proposals
  has_many :ratings, through: :proposals
  has_many :participant_invitations

  serialize :proposal_tags, Array
  serialize :review_tags, Array

  scope :recent, -> { order('name ASC') }
  scope :live, -> { where("state = 'open' and (closes_at is null or closes_at > ?)", Time.current).order('closes_at ASC') }

  validates :name, :contact_email, presence: true
  validates :slug, presence: true, uniqueness: true

  before_validation :generate_slug


  def valid_proposal_tags
    proposal_tags.join(', ')
  end

  def valid_proposal_tags=(tags_string)
    self.proposal_tags = Tagging.tags_string_to_array(tags_string)
  end

  def valid_review_tags
    review_tags.join(', ')
  end

  def valid_review_tags=(tags_string)
    self.review_tags = Tagging.tags_string_to_array(tags_string)
  end

  def generate_slug
    self.slug = name.parameterize if slug.blank?
  end

  def to_s
    name
  end

  def open?
    state == 'open' && (closes_at.nil? || closes_at > Time.current)
  end

  def closed?
    ! open?
  end

  def past_open?
    state == 'open' && closes_at < Time.current
  end

  def unmet_requirements_for_scheduling
    missing_prereqs = []

    missing_prereqs << "Event must have a start date" unless start_date
    missing_prereqs << "Event must have a end date" unless end_date

    unless rooms.size > 0
      missing_prereqs << "Event must have at least one room"
    end

    missing_prereqs
  end

  def archive
    if current?
      update_attribute(:archived, true)
    end
  end

  def unarchive
    if archived?
      update_attribute(:archived, false)
    end
  end

  def current?
    ! archived?
  end

  def cfp_opens
    opens_at && opens_at.to_s(:long_with_zone)
  end

  def cfp_closes
    closes_at && closes_at.to_s(:long_with_zone)
  end

  def conference_date(conference_day)
    start_date + (conference_day - 1).days
  end
end

# == Schema Information
#
# Table name: events
#
#  id                          :integer          not null, primary key
#  name                        :string(255)
#  slug                        :string(255)
#  url                         :string(255)
#  contact_email               :string(255)
#  state                       :string(255)      default("closed")
#  opens_at                    :datetime
#  closes_at                   :datetime
#  start_date                  :datetime
#  end_date                    :datetime
#  proposal_tags               :text
#  review_tags                 :text
#  guidelines                  :text
#  policies                    :text
#  speaker_notification_emails :hstore           default({"accept"=>"", "reject"=>"", "waitlist"=>""})
#  created_at                  :datetime
#  updated_at                  :datetime
#  archived                    :boolean          default(FALSE)
#
# Indexes
#
#  index_events_on_slug  (slug)
#

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  before_filter :require_event, only: [:destroy]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
			@event.participants.create(person: current_user, role: 'organizer')
      flash[:info] = 'Your event was saved.'
      redirect_to organizer_event_path(@event)
    else
      flash[:danger] = 'There was a problem saving your event; please review the form for issues and try again.'
      render :new
    end
  end

  def destroy
    @event.destroy
    flash[:info] = "Your event has been deleted."
    redirect_to events_path
  end

  def archive
    @event = Event.find_by_id(params[:event_id])
    if @event
      @event.archive
      flash[:warning] = "#{@event.name} is now archived."
    else
      flash[:danger] = "Event not found. Unable to archive."
    end
    redirect_to admin_events_path
  end

  def unarchive
    @event = Event.find_by_id(params[:event_id])
    if @event
      @event.unarchive
      flash[:warning] = "#{@event.name} is now current."
    else
      flash[:danger] = "Event not found. Unable to unarchive."
    end
    redirect_to admin_events_path
  end

  def index
    @events = Event.order("archived").all
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_event, only: [:show]

  def index
    render locals: {
      events: Event.recent.decorate
    }
  end

  def show
  end
end

app/controllers/organizer/events_controller.rb
class Organizer::EventsController < Organizer::ApplicationController

  def edit
    @partial = 'admin/events/form'
    if params[:form]
      @partial = "admin/events/#{params[:form]}"
    end
  end

  def show
    participants = @event.participants.includes(:person).recent
    rating_counts = @event.ratings.group(:person_id).count

    render locals: {
      event: @event.decorate,
      rating_counts: rating_counts,
      participants: participants
    }
  end

  def update
    if @event.update_attributes(event_params)
      flash[:info] = 'Your event was saved.'
      redirect_to organizer_event_path(@event)
    else
      flash[:danger] = 'There was a problem saving your event; please review the form for issues and try again.'
      render :edit
    end
  end

end

app/views/admin/events/_form.html.haml
.row
  %fieldset.col-md-6
    %h2 Event Information
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', placeholder: 'Name of the event'
    .form-group
      = f.label :contact_email
      = f.text_field :contact_email, class: 'form-control', placeholder: 'Event email'
    .form-group
      = f.label :slug
      = f.text_field :slug, class: 'form-control', placeholder: 'Slug for the event URL, may be left blank'
      %p.help-block The slug will be used in public facing URLs. If you leave this field blank, a slug will be generated based on the name.
    .form-group
      = f.label :url
      = f.text_field :url, class: 'form-control', placeholder: 'Event\'s URL'
  %fieldset.col-md-6
    %h3 CFP Dates
    .form-group
      = f.label :opens_at
      = f.object.cfp_opens
      = f.text_field :opens_at, value: (f.object.opens_at.blank? ? "" : f.object.opens_at.to_s(:long_with_zone) )
      -#%p.help-block Open proposal end date is optional. If you do not provide one the CFP will defer to its state.
    .form-group
      = f.label :closes_at
      = f.object.cfp_closes
      = f.text_field :closes_at, value: (f.object.closes_at.blank? ? "" : f.object.closes_at.to_s(:long_with_zone) )
      -#%p.help-block Open proposal end date is optional. If you do not provide one the CFP will defer to its state.
    %h3 Event Dates
    .form-group
      = f.label :start_date
      = f.object.start_date.to_s(:month_day_year) unless f.object.start_date.blank?
      = f.text_field :start_date, value: (f.object.start_date.blank? ? "" : f.object.start_date.to_s(:month_day_year) )
    .form-group
      = f.label :end_date
      = f.object.end_date.to_s(:month_day_year) unless f.object.end_date.blank?
      = f.text_field :end_date, value: (f.object.end_date.blank? ? "" : f.object.end_date.to_s(:month_day_year) )
      -#%p.help-block Open proposal end date is optional. If you do not provide one the CFP will defer to its state.
    .form-group
      = f.label :state
      = f.select :state, ['open', 'closed'], class: 'form-control'

.row.col-md-12.form-submit
  - if event && event.persisted? && current_user.admin?
    = link_to 'Delete Event', admin_event_path(event), method: :delete, data: { confirm: 'Are you sure you want to delete this event?' }, class: 'btn btn-danger pull-left'

  %button.pull-right.btn.btn-success{:type => "submit"} Save

app/views/admin/events/_guidelines_form.html.haml
.row
  %fieldset.col-md-6

    .form-group
    = f.label :guidelines
    = f.text_area :guidelines, class: 'form-control', placeholder: 'Description of CFP', rows: 20
    %p.help-block Markdown compatible
  %button.pull-right.btn.btn-success{:type => "submit"} Save

app/views/admin/events/_speaker_notifications_form.html.haml
.row
  %fieldset.col-md-6
    %h2 Speaker Notifications
    %p.help-block These fields control the text that is displayed in notification emails that are sent to speakers.
    - f.object.speaker_notification_emails.each do |type, text|
      .form-group
        = f.label type
        = f.text_area type, class: 'form-control', rows: 20, placeholder: "Please enter some text", value: text
  %fieldset.col-md-6
    .panel.panel-default
      .panel-heading
        .panel-title Email markup
    .panel-body
      %p Paragraphs are separated by two newlines.
      %p
        You can insert the proposal title using:
        %br
        %code ::proposal_title::
      %p
        You can insert the confirmation link* using:
        %br
        %code ::confirmation_link::
      %p
        You can insert the confirmation link with some link text using:
        %br
        %code ::This is my link text|confirmation_link::
      %p.help-block * confirmation link is not available in Reject emails
  %button.pull-right.btn.btn-success{:type => "submit"} Save

app/views/admin/events/_tags_form.html.haml
%h2 Tags
.form-group
  = f.label :valid_proposal_tags
  = f.text_field :valid_proposal_tags, class: 'form-control', placeholder: 'Separate multiple tags with commas'
  %p.help-block This is a comma separated list of tags allowed for use on proposals. These limits apply to publicly displayed tags and not to tags used internally by reviewers.

.form-group
  = f.label :valid_review_tags
  = f.text_field :valid_review_tags, class: 'form-control', placeholder: 'Separate multiple tags with commas'
  %p.help-block This is a comma separated list of tags allowed for use during proposal reviews. These limits apply to tags used internally by reviewers and not to publicly displayed tags.
  %button.pull-right.btn.btn-success{:type => "submit"} Save

app/views/admin/events/index.html.haml
.row
  .col-md-12
    .toolbox.pull-right
      = link_to 'Add Event', new_admin_event_path, class: "btn btn-primary"
.row
  .col-md-12
    %h2 Events
    %table.table.table-striped
      %thead
        %tr
          %th Event
          %th Dates
          %th Status
          %th CFP Opens At
          %th CFP Closes At
          %th Archive/Unarchive
        %tr
      %tbody
        - @events.each do |event|
          %tr
            %td= link_to event.name, organizer_event_path(event)
            %td= "#{event.start_date.to_s(:month_day) unless event.start_date.blank?} - #{event.end_date.to_s(:month_day_year) unless event.end_date.blank?}"
            %td= event.state
            %td= event.opens_at.to_s(:long_with_zone) unless event.opens_at.blank?
            %td= event.closes_at.to_s(:long_with_zone) unless event.closes_at.blank?
            - if event.current?
              %td= link_to "Archive", admin_event_archive_path(event), method: :post, class: "btn btn-danger btn-xs", data: {confirm: "This will hide this event from reviewers and organizers. Would you like to continue?" }
            - else
              %td= link_to "Unarchive", admin_event_unarchive_path(event), method: :post, class: "btn btn-success btn-xs"

app/views/admin/events/new.html.haml
%h1 Create a new event
= form_for event, url: admin_events_path, html: {role: 'form'} do |f|
  = render partial: 'form', locals: {f: f}